server {
    listen 80;
    
    # Onde os arquivos do build estarão
    root /usr/share/nginx/html;
    index index.html;

    # A mágica para SPA: se não achar o arquivo, serve o index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache para arquivos estáticos (opcional, mas bom para performance)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}